### ISSUE TITLE
Move modifiable files due to AppImage

### ISSUE THREAD

**Issue by Miepee** [Lojemiru/AM2R-Community-Updates#38]
**Is your feature request related to a problem? Please describe.**
When building an AppImage, the AppImage becomes read-only. Thus, if a player wanted to change some files (i.e. mods folder, lang folder or the modifiers.ini), they would have to modify the files in patch_data and then rebuild the whole AppImage. This not ideal.

**Describe the solution you'd like**
Move all files that are intended to be modified to i.e. .config/AM2R and load them from there.

**Describe alternatives you've considered**
Since running natively on Linux should be avoided at all costs, due to dependency hell, just editing the files in the asset folder and running the binary is not an option.
It *could* (=> I need to test this)  be possible to extract the AppImage via `./AM2R.AppImage --appimage-extract`. This would create a squashfs directory, which is editable. The binary in squashfs/usr/bin/ should pull all the dependencies from the squashfs folder, and not from the system. After they're done editing and want their AppImage back, they can just use the "CreateAppImage.sh" script in order to create it.
If this would be a viable option though, this should be mentioned somewhere.

And just as a FYI, trying to edit the files, while the AppImage is mounted does not work, as it's read-only.

**Comment by Lojemiru** [comment]
It is not feasible to specify a custom folder due to filesystem constraints. See https://docs.yoyogames.com/source/dadiospice/002_reference/file handling/file system limits.html for more information.

*However*, it may be possible to make a Linux-only featureset that allows these files to be read from the *save directory*. It's more convoluted to edit files there than from a custom folder, but it's the best option we have in GameMaker: Studio 1.4.

**Comment by Lojemiru** [comment]
Miepee has determined this as a non-issue; the AppImage can be easily modified.
